/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}

				<Script
					src="https://lora-sdk.belive.sg/player-widget/latest/player.min.js"
					strategy="beforeInteractive"
				></Script>
				<Script
					strategy="lazyOnload"
					src="https://lora-sdk.belive.sg/embed-js/latest/lora-embed.js"
				></Script>
			</body>
		</html>
	);
}
